CREATE TABLE IF NOT EXISTS Maquina (
Id_Maquina INT PRIMARY KEY NOT NULL,
Tipo VARCHAR(255),
Velocidade INT,
HardDisk INT,
Placa_Rede INT,
Memoria_Ram INT,
Fk_Usuario INT,
FOREIGN KEY(Fk_Usuario) REFERENCES Usuario(ID_Usuario) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS Usuario (
ID_Usuario INT PRIMARY KEY NOT NULL,
Password VARCHAR(255),
Nome_Usuario VARCHAR(255),
Ramal INT,
Especialidade VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS Software (
Id_Software INT PRIMARY KEY NOT NULL,
Produto VARCHAR(255),
HardDisk INT,
Memoria_Ram INT,
Fk_Maquina INT,
FOREIGN KEY(Fk_Maquina) REFERENCES Maquina(Id_Maquina) ON DELETE CASCADE
);

SELECT * FROM USUARIO;

DROP TABLE USUARIO;
DROP TABLE MAQUINA;
DROP TABLE SOFTWARE;